blogapp/urls.py
from django.urls import path
from blogapp.views import home_view, connexion_view, inscription_view, deconnexion_view, create_article_view, detail_article_view, update_article_view, delete_article_view

 
app_name = 'blogapp'

urlpatterns = [
    path('', home_view, name='home'),
    path('connexion/', connexion_view, name='connexion'),
    path('inscription/', inscription_view, name='inscription'),
    path('deconnexion/', deconnexion_view, name='deconnexion'),
    
    path('article/create/', create_article_view, name='create_article'),
    path('article/<int:pk>/', detail_article_view, name='detail_article'),
    path('article/<int:pk>/update/', update_article_view, name='update_article'),
    path('article/<int:pk>/delete/', delete_article_view, name='delete_article'),
] 

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User

# models

# article model
class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(
        to=User, 
        on_delete=models.PROTECT,
        related_name='articles',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"${self.title}"

blogapp/forms.py
from django import forms

from blogapp.models import Article

class ArticleForms(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content']

blogapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout

from blogapp.forms import ArticleForms
from blogapp.models import Article


# views.py

# home view
def home_view(request):
    articles = Article.objects.all().order_by('-created_at')
    context = {
        'articles': articles,
    }
    return render(request, 'home.html', context)

def connexion_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('blogapp:home')
    else:
        form = AuthenticationForm()
    return render(request, 'connexion.html', {'form': form})

# inscription view
def inscription_view(request):
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('blogapp:home')
        
    else:
        form = UserCreationForm()
    return render(request, 'inscription.html', {'form': form})


# logout view
def deconnexion_view(request):
    
    logout(request)
    return redirect('blogapp:home')


@login_required
def create_article_view(request):
    if request.method == 'POST':
        form = ArticleForms(request.POST)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.author = request.user
            new_article.save()
            return redirect('blogapp:home')
        
    else:
        form = ArticleForms()
        
    return render(
        request, 
        'create_update_article.html', 
        {'form': form, 
        'action': 'Creer'
    })
    
def detail_article_view(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'detail_article.html', context)


@login_required
def update_article_view(request, pk):
    article = get_object_or_404(Article, pk=pk)
    
    if article.author != request.user:
        return redirect('blogapp:home', pk=article.pk)
    
    
    if request.method == 'POST':
        form = ArticleForms(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('blogapp:detail_article', pk=article.pk)
        
    else:
        form = ArticleForms(instance=article)
        
    context = {
        'form': form,
        'action' : 'Modifier',
        'article': article,
    }
        
    return render(
        request, 
        'create_update_article.html', 
        context
    )
    
    
@login_required
def delete_article_view(request, pk):
    article = get_object_or_404(Article, pk=pk)
    
    if article.author != request.user:
        return redirect('blogapp:detail_article', pk=article.pk)
    
    if request.method == 'POST':
        article.delete()
        return redirect('blogapp:home')
    
    context = {
        'article': article,
    }
    
    return render(request, 'delete_article.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Mon Blog{% endblock %}</title>
    <style>
      body {
        font-family: sans-serif;
        margin: 20;
        padding: 0;
        background-color: #f4f4f4;
        color: #333;
      }
      nav {
        background-color: #333;
        padding: 10px;
        margin-bottom: 20px;
      }
      nav a {
        color: white;
        margin-right: 15px;
        text-decoration: none;
      }
      .container {
        margin: 0 auto;
        padding: 20px;
        background-color: white;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      h1,
      h2,
      h3 {
        color: #555;
      }
    </style>
  </head>
  <body>
    <nav>
      <a href="{% url 'blogapp:home' %}">Accueil</a>

      {% if user.is_authenticated %}
      <a href="#">{{ user.username.upper }}</a>
      <a href="{% url 'blogapp:create_article' %}"> + Créer un article</a>
      <a href="{% url 'blogapp:deconnexion' %}">Deconnexion</a>

      {% else %}
      <a href="{% url 'blogapp:connexion' %}">Connexion</a>
      <a href="{% url 'blogapp:inscription' %}">Inscription</a>
      {% endif %}
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
  </body>
</html>

templates/connexion.html
{% extends 'base.html' %} {% block title %} Connexion {% endblock title %}
<!--  -->
{%block content %}
<h2>Page de connexion</h2>

<form method="post">
  {% csrf_token %}
  <!--  -->
  {{ form.as_p }}
  <button type="submit">Connexion</button>
</form>
{% endblock content %}

templates/create_update_article.html
{% extends 'base.html' %} {% block title %}{{action}} Article
<!--  -->
{% endblock title%}
<!--  -->
{%block content %}
<h2>{{action}} un Arricle</h2>

<form method="post">
  {% csrf_token %} {{ form.as_p}}
  <button>{{action}}</button>
</form>

{% endblock content %}

templates/delete_article.html
{% extends 'base.html' %} {% block title %} supression d'un Article
<!--  -->
{% endblock title%} {% block content %}

<h2>Supprimer l'Article</h2>
<form method="post">
  {% csrf_token %}
  <p>
    Êtes-vous sûr de vouloir supprimer l'article :
    <strong> {{ article.title }} </strong>
  </p>
  <small>Cette action est irréversible</small><br /><br />
  <button type="submit" class="btn btn-danger">Oui, Supprimer</button>
  -
  <a
    href="{% url 'blogapp:detail_article' pk=article.pk %}"
    class="btn btn-secondary"
    >Non, Annuler</a
  >
</form>
<br />
{% if messages %}
<div class="alert alert-warning">
  {% for message in messages %}
  <p>{{ message }}</p>
  {% endfor %}
</div>
{% endif %}
<!--  -->

{% endblock content %}

templates/detail_article.html
{% extends 'base.html' %} {% block title %} {{article.title}}
<!--  -->
{% endblock title%}
<!--  -->
{%block content %}

<h1>{{article.title}}</h1>
<hr />
<small>
  Par: <b>{{article.author.username.capitalize}}</b> - Le {{article.created_at}}
  <!-- verifier si l'article a ete mis a jour -->
  {% if article.created_at != article.updated_at %} - Mis à jour le
  {{article.updated_at}}
  <!--  -->
  {% endif %}
</small>
<hr />
<br />

<div>{{ article.content|linebreaks }}</div>

<br />
<br />
{% if user.is_authenticated and user == article.author %}

<hr />
<a
  href="{% url 'blogapp:update_article' pk=article.pk%}"
  class="btn btn-primary"
>
  Modifier cet Article
  <!--  -->
</a>
-

<a href="{% url 'blogapp:delete_article' pk=article.pk%}" class="btn btn-danger"
  >Supprimer cet Article</a
>
<!--  -->
<hr />
{% endif%}
<!--  -->
{% endblock content %}

templates/home.html
{% extends 'base.html' %} {% block title %} Accueil {% endblock title %}
<!--  -->
{%block content %}
<h2>Page d'accueil</h2>
<hr />

<h3>Bienvenue sur notre blog</h3>

{% if user.is_authenticated %}
<p>
  Bonjour vous êtes connecté étant que
  <a href="#">{{ user.username.upper }}</a> -
  <a href="{% url 'blogapp:create_article' %}">Ajouter un article</a>
</p>
{% else %}
<p>Veillez vous connecter</p>
{% endif %}
<hr />

<h3>Nos derniers articles</h3>

{% if articles %}
<!--  -->

<ul>
  {% for article_item in articles %}
  <li>
    <h4>
      <a href="{% url 'blogapp:detail_article' pk=article_item.pk %}"
        >{{ article_item.title }}</a
      >
    </h4>
    <p>
      Par: <b>{{ article_item.author.username.capitalize }}</b> -
      <!--  -->
      Publié le {{ article_item.created_at }}
    </p>
  </li>
  {% endfor %}
</ul>

{% else %}
<p>
  Aucun article n'est disponible pour le moment. Soyez le premier à en écrire un
  !
</p>
{% endif %}

<!--  -->
{% endblock content %}

templates/inscription.html
{% extends 'base.html' %} {% block title %} Inscription {% endblock title %}
<!--  -->
{%block content %}
<h2>Page d'inscription</h2>

<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">S'inscrire</button>
</form>
{% endblock content %}